---

- ansible.builtin.include_tasks:
    file: user.yml
  when: concourse_manage_user

- ansible.builtin.include_tasks:
    file: install.yml
- ansible.builtin.include_tasks:
    file: configure.yml
- ansible.builtin.include_tasks:
    file: start.yml

- shell: /bin/true
  when: concourse_force_restart
  notify:
    - restart concourse web
    - restart concourse worker
