---
- name: main - print extra info
  ansible.builtin.debug:
    msg:
      - "concourse_baggageclaim_driver: {{ concourse_baggageclaim_driver }}"

- include: user.yml
  when: concourse_manage_user

- include: install.yml
- include: configure.yml
- include: start.yml

- shell: /bin/true
  when: concourse_force_restart
  notify:
  - restart concourse web
  - restart concourse worker
