- name: stop web
  service:
    name: concourse-web
    state: stopped
  become: true
  ignore_errors: true
  when: concourse_web
  tags:
  - no-test

- name: stop worker
  service:
    name: concourse-worker
    state: stopped
  become: true
  ignore_errors: true
  when: concourse_worker
  tags:
  - no-test
