---
- name: concourse group
  group:
    name: "{{ concourse_group }}"
    gid: "{{ concourse_gid }}"
  become: true

- name: concourse user
  user:
    name: "{{ concourse_user }}"
    comment: Concourse CI
    uid: "{{ concourse_uid }}"
    group: "{{ concourse_group }}"
    shell: "/bin/false"
    createhome: false
  become: true
